<?xml version="1.0" encoding="utf-8"?><Database Name="SportStoreDB" Class="SportStoreDContextDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-P4F5KURV;Initial Catalog=SportStoreDB;Integrated Security=True;Pooling=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SportStoreDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Shoes" Member="Shoes">
    <Type Name="Shoe">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Company" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsSale" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Pic" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SportEquipments" Member="SportEquipments">
    <Type Name="SportEquipment">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WhatSport" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Company" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TeamId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Pic" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Team_SportEquipment" Member="Team" ThisKey="TeamId" OtherKey="Id" Type="Team" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Teams" Member="Teams">
    <Type Name="Team">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TeamName" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="Team_SportEquipment" Member="SportEquipments" ThisKey="Id" OtherKey="TeamId" Type="SportEquipment" />
    </Type>
  </Table>
  <Table Name="dbo.Clothes" Member="Clothes">
    <Type Name="Clothe">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ClothType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Brand" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="isShort" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="isDrifit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Pic" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Price" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>